#ifndef PUBLIC_FPDF_COMPRESS_H_
#define PUBLIC_FPDF_COMPRESS_H_

#include "fpdfview.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct fpdf_compress_options_t__* FPDF_COMPRESS_OPTIONS;

#define HYPERC_OPT_IMAGE_MAX_DPI 1

#define HYPERC_OPT_IMAGE_THRESHOLD_DPI 50

#define HYPERC_OPT_IMAGE_RESAMPLE_QUALITY 52
#define HYPERC_RESAMPLE_NEAREST 0
#define HYPERC_RESAMPLE_BILINEAR 1
#define HYPERC_RESAMPLE_HIGH 2

#define HYPERC_OPT_JPEG_SUBSAMPLE 53
#define HYPERC_JPEG_SUBSAMPLE_DEFAULT 0
#define HYPERC_JPEG_SUBSAMPLE_420 1
#define HYPERC_JPEG_SUBSAMPLE_422 2
#define HYPERC_JPEG_SUBSAMPLE_444 3
#define HYPERC_OPT_JPEG_OPTIM_HUFFMAN 54
#define HYPERC_OPT_JPEG_PROGRESSIVE 55

#define HYPERC_OPT_IMAGE_QUALITY 2

#define HYPERC_OPT_IMAGE_ENCODING 3
#define HYPERC_IMAGE_ENCODING_PRESERVE 0
#define HYPERC_IMAGE_ENCODING_JPEG 1
#define HYPERC_IMAGE_ENCODING_FLATE 2
#define HYPERC_IMAGE_ENCODING_JPEG2000 3
#define HYPERC_IMAGE_ENCODING_AUTO 4

#define HYPERC_OPT_IMAGE_GRAYSCALE 5

#define HYPERC_OPT_IMAGE_COLOR_TARGET 51
#define HYPERC_COLOR_TARGET_ORIGINAL 0
#define HYPERC_COLOR_TARGET_SRGB 1
#define HYPERC_COLOR_TARGET_CMYK 2
#define HYPERC_COLOR_TARGET_GRAY 3

#define HYPERC_OPT_CLIP_IMAGES 6

#define HYPERC_OPT_REDUCE_COLOR_COMPLEXITY 7

#define HYPERC_OPT_IMAGE_INDEX_MIN_DPI 56

#define HYPERC_OPT_IMAGE_COLOR_MAX_DPI 57
#define HYPERC_OPT_IMAGE_GRAY_MAX_DPI 58
#define HYPERC_OPT_IMAGE_MONO_MAX_DPI 59

#define HYPERC_OPT_IMAGE_LOSSY_INDEX 63

#define HYPERC_OPT_IMAGE_PREFER_JPX 18

#define HYPERC_OPT_FONT_SUBSET 10

#define HYPERC_OPT_FONT_REMOVE_STANDARD 12

#define HYPERC_OPT_UNEMBED_ALIASED_FONTS 9

#define HYPERC_OPT_FONT_MERGE 13

#define HYPERC_OPT_FONT_DEDUP_DICTS 14

#define HYPERC_OPT_DEDUP_OBJECTS 16

#define HYPERC_OPT_OPTIMIZE_RESOURCES 17

#define HYPERC_OPT_FLATTEN_ICC 8

#define HYPERC_OPT_DISCARD_MASK 20

#define HYPERC_DISCARD_STRUCT_TREE 0x00000001
#define HYPERC_DISCARD_THUMBNAILS 0x00000002
#define HYPERC_DISCARD_BOOKMARKS 0x00000004
#define HYPERC_DISCARD_ANNOTATIONS 0x00000008
#define HYPERC_DISCARD_FORM_FIELDS 0x00000010
#define HYPERC_DISCARD_FILE_ATTACHMENTS 0x00000020
#define HYPERC_DISCARD_ALTERNATE_IMAGES 0x00000040
#define HYPERC_DISCARD_PIECE_INFO 0x00000080
#define HYPERC_DISCARD_INFO_METADATA 0x00000100
#define HYPERC_DISCARD_PRINT_SETTING 0x00000200
#define HYPERC_DISCARD_SEARCH_INDEX 0x00000400
#define HYPERC_DISCARD_NAMED_DESTS 0x00000800
#define HYPERC_DISCARD_ACTIONS 0x00001000
#define HYPERC_DISCARD_PAGE_PIECE_INFO 0x00002000
#define HYPERC_DISCARD_OUTPUT_INTENTS 0x00004000
#define HYPERC_DISCARD_ARTICLE_THREADS 0x00008000
#define HYPERC_DISCARD_SIG_APPEARANCES 0x00010000
#define HYPERC_DISCARD_LINKS 0x00020000

#define HYPERC_FLATTEN_ANNOTS_KEEP_FORMS_LINKS 0x00040000

#define HYPERC_DISCARD_SPIDER_INFO 0x00080000

#define HYPERC_FLATTEN_FORMS 0x00100000
#define HYPERC_FLATTEN_LINKS 0x00200000

#define HYPERC_OPT_MRC_MODE 40
#define HYPERC_MRC_OFF 0
#define HYPERC_MRC_AUTO 1
#define HYPERC_MRC_FORCE 2

#define HYPERC_OPT_MRC_SELECTOR_DPI 41

#define HYPERC_OPT_MRC_BG_DPI 42

#define HYPERC_OPT_MRC_BG_QUALITY 43
#define HYPERC_OPT_MRC_FG_QUALITY 44

#define HYPERC_OPT_CONVERT_TO_BITMAP 60
#define HYPERC_OPT_CONVERT_TO_BITMAP_DPI 61
#define HYPERC_OPT_CONVERT_TO_BITMAP_QUALITY 62

#define HYPERC_OPT_RECOMPRESS_CONTENT_STREAMS 30

#define HYPERC_OPT_PDFA_MODE 64

#define HYPERC_OPT_STREAM_CODEC 65

#define HYPERC_OPT_BROTLI_QUALITY 66

FPDF_EXPORT FPDF_COMPRESS_OPTIONS FPDF_CALLCONV
HyperCompress_CreateOptions(void);

FPDF_EXPORT void FPDF_CALLCONV
HyperCompress_SetOption(FPDF_COMPRESS_OPTIONS opts, int option, int value);

FPDF_EXPORT int FPDF_CALLCONV
HyperCompress_GetOption(FPDF_COMPRESS_OPTIONS opts, int option);

FPDF_EXPORT void FPDF_CALLCONV
HyperCompress_CloseOptions(FPDF_COMPRESS_OPTIONS opts);

FPDF_EXPORT int FPDF_CALLCONV
HyperCompress_Execute(FPDF_DOCUMENT document, FPDF_COMPRESS_OPTIONS opts);

#define HYPERC_EXEC_SKIPPED_SIGNED 2

FPDF_EXPORT int FPDF_CALLCONV
HyperCompress_DocIsSigned(FPDF_DOCUMENT document);

#ifdef __cplusplus
}
#endif

#endif
